export const MOCK_PRODUCTS = [
  {
    id: "mock-1",
    slug: "gold-bar-1-oz",
    sku: "GB-1OZ-LBMA",
    name: "1 oz Gold Bar — LBMA Certified",
    description: "A 1 troy ounce gold bar, LBMA-certified with .9999 purity. Each bar is individually serialized and assayed, ensuring its weight, purity, and authenticity. Sourced from LBMA-accredited refiners.",
    shortDescription: "1 oz .9999 pure gold bar with LBMA certification and individual serial number.",
    type: "bar",
    weightGrams: 31.1035,
    weightTroyOz: 1,
    purityPercent: 99.99,
    manufacturer: "Various LBMA Refiners",
    countryOfOrigin: null,
    year: null,
    markupPercent: 1.5,
    buybackMarkupPct: -0.5,
    stockQuantity: 47,
    isFeatured: true,
    isIrsReportable: true,
    metaTitle: "1 oz Gold Bar | LBMA Certified .9999 | AUREUM GOLD",
    metaDescription: "Invest in 1 oz LBMA-certified gold bars with .9999 purity. Serialized, assayed, and fully insured.",
    images: [{ url: "/images/products/gold-bar-1oz.jpg", altText: "1 oz Gold Bar", isPrimary: true, sortOrder: 0 }],
    categories: [{ category: { slug: "bars" } }, { category: { slug: "investment-grade" } }],
  },
  {
    id: "mock-2",
    slug: "gold-bar-10-oz",
    sku: "GB-10OZ-LBMA",
    name: "10 oz Gold Bar — LBMA Certified",
    description: "A 10 troy ounce gold bar, LBMA-certified with .9999 purity. These larger bars offer a more cost-effective way to invest in physical gold, with a lower premium over spot price.",
    shortDescription: "10 oz .9999 pure gold bar — lower premium over spot, ideal for serious investors.",
    type: "bar",
    weightGrams: 311.035,
    weightTroyOz: 10,
    purityPercent: 99.99,
    manufacturer: "Various LBMA Refiners",
    countryOfOrigin: null,
    year: null,
    markupPercent: 0.8,
    buybackMarkupPct: -0.3,
    stockQuantity: 23,
    isFeatured: true,
    isIrsReportable: true,
    metaTitle: "10 oz Gold Bar | LBMA Certified | AUREUM GOLD",
    metaDescription: "10 oz LBMA-certified gold bars at competitive premiums. .9999 purity, serialized and fully insured.",
    images: [{ url: "/images/products/gold-bar-10oz.jpg", altText: "10 oz Gold Bar", isPrimary: true, sortOrder: 0 }],
    categories: [{ category: { slug: "bars" } }, { category: { slug: "investment-grade" } }],
  },
  {
    id: "mock-3",
    slug: "gold-american-eagle-1-oz",
    sku: "COIN-AE-1OZ",
    name: "American Gold Eagle 1 oz — BU",
    description: "The American Gold Eagle is the official gold bullion coin of the United States. Minted by the US Mint since 1986, it contains 1 troy ounce of gold and is guaranteed for weight and purity. In Brilliant Uncirculated condition.",
    shortDescription: "US Mint American Gold Eagle 1 oz. Legal tender, .9167 purity, BU condition.",
    type: "coin",
    weightGrams: 33.93,
    weightTroyOz: 1,
    purityPercent: 91.67,
    manufacturer: "United States Mint",
    countryOfOrigin: "United States",
    year: 2024,
    markupPercent: 4.5,
    buybackMarkupPct: -1.0,
    stockQuantity: 89,
    isFeatured: true,
    isIrsReportable: true,
    metaTitle: "American Gold Eagle 1 oz | US Mint | AUREUM GOLD",
    metaDescription: "Purchase 1 oz American Gold Eagle coins. US legal tender, .9167 purity, Brilliant Uncirculated.",
    images: [{ url: "/images/products/gold-eagle-1oz.jpg", altText: "American Gold Eagle 1 oz", isPrimary: true, sortOrder: 0 }],
    categories: [{ category: { slug: "coins" } }, { category: { slug: "us-mint" } }],
  },
  {
    id: "mock-4",
    slug: "gold-bar-100-oz",
    sku: "GB-100OZ-COMEX",
    name: "100 oz Gold Bar — COMEX Good Delivery",
    description: "A 100 troy ounce gold bar meeting COMEX Good Delivery standards. .9999 fine gold, serialized and assayed. For the serious institutional investor seeking the lowest premium over spot.",
    shortDescription: "100 oz COMEX Good Delivery gold bar. .9999 purity, lowest premium available.",
    type: "bar",
    weightGrams: 3110.35,
    weightTroyOz: 100,
    purityPercent: 99.99,
    manufacturer: "Various COMEX Refiners",
    countryOfOrigin: null,
    year: null,
    markupPercent: 0.3,
    buybackMarkupPct: -0.2,
    stockQuantity: 5,
    isFeatured: false,
    isIrsReportable: true,
    metaTitle: "100 oz Gold Bar | COMEX Good Delivery | AUREUM GOLD",
    metaDescription: "100 oz COMEX Good Delivery gold bars at institutional pricing. .9999 purity, serialized and assayed.",
    images: [{ url: "/images/products/gold-bar-100oz.jpg", altText: "100 oz Gold Bar", isPrimary: true, sortOrder: 0 }],
    categories: [{ category: { slug: "bars" } }, { category: { slug: "institutional" } }],
  },
  {
    id: "mock-5",
    slug: "gold-canadian-maple-leaf-1-oz",
    sku: "COIN-ML-1OZ",
    name: "Canadian Gold Maple Leaf 1 oz — BU",
    description: "The Canadian Gold Maple Leaf is one of the world's most popular gold bullion coins. Minted by the Royal Canadian Mint since 1979, it features .9999 pure gold and the iconic maple leaf design. Brilliant Uncirculated.",
    shortDescription: "Royal Canadian Mint Gold Maple Leaf 1 oz. .9999 pure gold, BU condition.",
    type: "coin",
    weightGrams: 31.1035,
    weightTroyOz: 1,
    purityPercent: 99.99,
    manufacturer: "Royal Canadian Mint",
    countryOfOrigin: "Canada",
    year: 2024,
    markupPercent: 3.8,
    buybackMarkupPct: -0.8,
    stockQuantity: 62,
    isFeatured: true,
    isIrsReportable: true,
    metaTitle: "Canadian Gold Maple Leaf 1 oz | RCM | AUREUM GOLD",
    metaDescription: "Buy 1 oz Canadian Gold Maple Leaf coins. .9999 pure gold, Brilliant Uncirculated, Royal Canadian Mint.",
    images: [{ url: "/images/products/gold-maple-leaf-1oz.jpg", altText: "Canadian Gold Maple Leaf 1 oz", isPrimary: true, sortOrder: 0 }],
    categories: [{ category: { slug: "coins" } }, { category: { slug: "royal-canadian-mint" } }],
  },
  {
    id: "mock-6",
    slug: "gold-bar-5-oz",
    sku: "GB-5OZ-PAMP",
    name: "5 oz Gold Bar — PAMP Suisse",
    description: "A 5 troy ounce gold bar from PAMP Suisse, one of the world's most prestigious refiners. .9999 purity with the iconic Lady Fortuna design. Each bar comes with an assay card and is individually serialized.",
    shortDescription: "5 oz PAMP Suisse gold bar. .9999 purity with assay card and serial number.",
    type: "bar",
    weightGrams: 155.5175,
    weightTroyOz: 5,
    purityPercent: 99.99,
    manufacturer: "PAMP Suisse",
    countryOfOrigin: "Switzerland",
    year: null,
    markupPercent: 2.0,
    buybackMarkupPct: -0.6,
    stockQuantity: 15,
    isFeatured: false,
    isIrsReportable: true,
    metaTitle: "5 oz PAMP Suisse Gold Bar | Lady Fortuna | AUREUM GOLD",
    metaDescription: "5 oz PAMP Suisse gold bar with assay card. .9999 purity, Lady Fortuna design, serialized.",
    images: [{ url: "/images/products/gold-bar-5oz-pamp.jpg", altText: "5 oz PAMP Suisse Gold Bar", isPrimary: true, sortOrder: 0 }],
    categories: [{ category: { slug: "bars" } }, { category: { slug: "premium" } }],
  },
  {
    id: "mock-7",
    slug: "gold-krugerrand-1-oz",
    sku: "COIN-KR-1OZ",
    name: "Gold Krugerrand 1 oz — BU",
    description: "The Gold Krugerrand is the world's most widely held gold bullion coin. First minted in 1967 by the South African Mint, it contains 1 troy ounce of gold. Its durability makes it ideal for handling and storage.",
    shortDescription: "South African Gold Krugerrand 1 oz. The world's most traded gold bullion coin.",
    type: "coin",
    weightGrams: 33.93,
    weightTroyOz: 1,
    purityPercent: 91.67,
    manufacturer: "South African Mint",
    countryOfOrigin: "South Africa",
    year: 2024,
    markupPercent: 3.5,
    buybackMarkupPct: -0.8,
    stockQuantity: 104,
    isFeatured: false,
    isIrsReportable: true,
    metaTitle: "Gold Krugerrand 1 oz | South African Mint | AUREUM GOLD",
    metaDescription: "Buy 1 oz Gold Krugerrand coins. The world's most popular bullion coin, .9167 purity, BU.",
    images: [{ url: "/images/products/gold-krugerrand-1oz.jpg", altText: "Gold Krugerrand 1 oz", isPrimary: true, sortOrder: 0 }],
    categories: [{ category: { slug: "coins" } }, { category: { slug: "sovereign" } }],
  },
  {
    id: "mock-8",
    slug: "gold-bar-1-gram",
    sku: "GB-1G-VALUEPACK",
    name: "1 Gram Gold Bar — Value Pack (10)",
    description: "Ten 1 gram gold bars from LBMA-approved refiners. Each bar is .9999 pure gold with its own assay card. Ideal for gifting, barter, or starting a gold stacking journey. Housed in a sealed presentation pack.",
    shortDescription: "10x 1 gram .9999 gold bars with assay cards in presentation pack.",
    type: "bar",
    weightGrams: 10,
    weightTroyOz: 0.3215,
    purityPercent: 99.99,
    manufacturer: "Various LBMA Refiners",
    countryOfOrigin: null,
    year: null,
    markupPercent: 15.0,
    buybackMarkupPct: -5.0,
    stockQuantity: 200,
    isFeatured: false,
    isIrsReportable: false,
    metaTitle: "1 Gram Gold Bar Value Pack (10) | AUREUM GOLD",
    metaDescription: "10x 1g gold bars with assay cards. .9999 purity, LBMA-approved refiners, presentation pack.",
    images: [{ url: "/images/products/gold-bar-1g-pack.jpg", altText: "1 Gram Gold Bar Value Pack", isPrimary: true, sortOrder: 0 }],
    categories: [{ category: { slug: "bars" } }, { category: { slug: "fractional" } }],
  },
];

export const MOCK_GOLD_PRICE = {
  xauUsd: 2342.15,
  changeUsd: 12.45,
  changePct: 0.53,
  direction: "up" as const,
  fetchedAt: new Date().toISOString(),
  source: "mock",
};

export function isDbUnavailable(error: unknown): boolean {
  const msg = String(error);
  return msg.includes("DATABASE_URL") || msg.includes("PrismaPg") || msg.includes("connection") || msg.includes("prisma");
}
